server:
  port: 8080
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5

  datasource:
    url: jdbc:mysql://localhost:3306/tree?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:com/fums/**/mapper/*.xml
  type-aliases-package: com.fums.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
