server:
  port: 8080
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5

  datasource:
    url: jdbc:mysql://localhost:3306/tree?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    redis:
      host: 192.168.202.128
      port: 6379
      password: 123456
      database: 0
      jedis:
        pool:
          max-idle: 6
          max-active: 32

mybatis:
  mapper-locations: classpath:com/fums/**/mapper/*.xml
  type-aliases-package: com.fums.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
